version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  backend:
    build: ./backend/foodgram/
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
