# Generated by Django 5.1 on 2024-09-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeshortlink_short_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeshortlink',
            options={'verbose_name': 'сокращённая ссылка', 'verbose_name_plural': 'Сокращённые ссылки'},
        ),
    ]
